# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: login.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'login.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x05login\"/\n\x12PostMessageRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"%\n\x12PostMessageSuccess\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x13\n\x11GetMessageRequest\"%\n\x12GetMessageResponce\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9c\x01\n\x0eLoggingService\x12\x43\n\x0bPostMessage\x12\x19.login.PostMessageRequest\x1a\x19.login.PostMessageSuccess\x12\x45\n\x0eGetAllMessages\x12\x18.login.GetMessageRequest\x1a\x19.login.GetMessageResponceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTMESSAGEREQUEST']._serialized_start=22
  _globals['_POSTMESSAGEREQUEST']._serialized_end=69
  _globals['_POSTMESSAGESUCCESS']._serialized_start=71
  _globals['_POSTMESSAGESUCCESS']._serialized_end=108
  _globals['_GETMESSAGEREQUEST']._serialized_start=110
  _globals['_GETMESSAGEREQUEST']._serialized_end=129
  _globals['_GETMESSAGERESPONCE']._serialized_start=131
  _globals['_GETMESSAGERESPONCE']._serialized_end=168
  _globals['_LOGGINGSERVICE']._serialized_start=171
  _globals['_LOGGINGSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
